import { BiMenu, BiSolidShoppingBags } from "react-icons/bi";
import { BsSmartwatch, BsPhone } from "react-icons/bs";
import { FaTshirt } from "react-icons/fa";
import { FaComputer } from "react-icons/fa6";
import { AiOutlineClose } from "react-icons/ai";
import { PiTelevisionFill } from "react-icons/pi";
import { MdOutlineWatch } from "react-icons/md";
import { IoBedOutline } from "react-icons/io5";
import { GoKebabHorizontal } from "react-icons/go";
const categories = [
  {
    id: 1,
    name: "Fashion",
    slug: "fashion",
    description:
      "Explore the latest trends in clothing, footwear, and accessories. Find stylish options in categories like Clothing and Footwear.",
    icon: FaTshirt,
    image: "",
  },
  {
    id: 2,
    name: "Electronics",
    slug: "electronics",
    description:
      "Discover cutting-edge electronics, including Smartphones, Tablets, and Computers. Stay up-to-date with the latest technology trends.",
    icon: PiTelevisionFill,
    image: "",
  },
  {
    id: 3,
    name: "Phones",
    slug: "phones",
    description:
      "Stay connected with the best mobile phones. Explore our collection of Phones and Tablets for the latest models.",
    icon: BsPhone,
    image: "",
  },
  {
    id: 4,
    name: "Computers",
    slug: "computers",
    description:
      "Enhance your productivity with powerful laptops and desktops. Shop in the Computers category for top computing solutions.",
    icon: FaComputer,
    image: "",
  },
  {
    id: 5,
    name: "Watches",
    slug: "watches",
    description:
      "Stay punctual and fashionable with our premium Watch collection. Choose from a variety of stylish timepieces.",
    icon: BsSmartwatch,
    image: "",
  },
  {
    id: 6,
    name: "Digital Watches",
    slug: "digital-watches",
    description:
      "Experience the future of timekeeping with Digital Watches. Discover our range of smart timepieces.",
    icon: MdOutlineWatch,
    image: "",
  },
  {
    id: 7,
    name: "Beddings",
    slug: "beddings",
    description:
      "Rest in comfort with our high-quality Beddings. Explore options like Bedsheets and Pillows for a good night's sleep.",
    icon: IoBedOutline,
    image: "",
  },
  {
    id: 8,
    name: "Bags",
    slug: "bags",
    description:
      "Carry your essentials in style with our Bags collection. Find a variety of fashionable bags for every occasion.",
    icon: BiSolidShoppingBags,
    image: "",
  },
];
const subCategories = [
  //Fashion
  { id: 1, catId: 1, title: "Shoes" },
  { id: 2, catId: 1, title: "Pants" },
  { id: 3, catId: 1, title: "Shirts" },
  { id: 4, catId: 1, title: "T-Shirts" },
  { id: 5, catId: 1, title: "Jackets" },
  { id: 6, catId: 1, title: "Sweaters" },
  { id: 7, catId: 1, title: "Suits" },
  { id: 27, catId: 1, title: "Belt $ wallets" },
  //Electronics
  { id: 8, catId: 2, title: "Fridges" },
  { id: 9, catId: 2, title: "TVs" },
  { id: 10, catId: 2, title: "Woofers" },
  //Phones
  { id: 11, catId: 3, title: "Samsung" },
  { id: 12, catId: 3, title: "Iphone" },
  { id: 13, catId: 3, title: "Tecno" },
  { id: 14, catId: 3, title: "Nokia" },
  //computers
  { id: 15, catId: 4, title: "HP" },
  { id: 16, catId: 4, title: "DELL" },
  { id: 17, catId: 4, title: "LENOVO" },
  //watches
  { id: 18, catId: 5, title: "WATCHES FOR MEN" },
  { id: 19, catId: 5, title: "WATCHES FOR WOMEN" },
  //digital watches
  { id: 20, catId: 6, title: "Digital watches" },
  //beddings
  { id: 21, catId: 7, title: "Blankets" },
  { id: 22, catId: 7, title: "Duvet" },
  { id: 23, catId: 7, title: "Piliow cases" },
  //bags
  { id: 24, catId: 8, title: "School bags" },
  { id: 25, catId: 8, title: "Hand bags" },
  { id: 26, catId: 8, title: "Travell bags" },
];


// Assuming exchange rates (replace these with actual rates)
const ugxToUsdExchangeRate = 1 / 3500;  // 1 UGX to USD
const kesToUgxExchangeRate = 5;   // Current 1 USD to KES

// Your array of JSON objects
const products = [
  //SHOES
    {
      id: 1,
      title: "Suede Shoes",
      image: "/shoes/suede/4.jpg",
      slug: "suede-shoes",
      subCatId: 1,
      catId: 1,
      description: "Classic suede shoes for a sophisticated look.",
      hasFreeDelivery: true,
      currentPrice: 150000,
      originalPrice: 220000,
      subCatName: "Shoes",
      images: [
        "/shoes/suede/1.jpg",
        "/shoes/suede/2.jpg",
        "/shoes/suede/3.jpg",
        "/shoes/suede/4.jpg",
        "/shoes/suede/5.jpg",
        "/shoes/suede/6.jpg",
        "/shoes/suede/7.jpg",
        "/shoes/suede/8.jpg",
        "/shoes/suede/9.jpg",
        "/shoes/suede/10.jpg",
        "/shoes/suede/12.jpg",
        "/shoes/suede/13.jpg",
        "/shoes/suede/14.jpg",
        "/shoes/suede/15.jpg",
        "/shoes/suede/16.jpg",
        "/shoes/suede/17.jpg",
        "/shoes/suede/18.jpg",
        "/shoes/suede/19.jpg",
        "/shoes/suede/21.jpg",
      ],
    },
    {
      id: 2,
      title: "Mocasin",
      image: "/shoes/mocasin/19.jpg",
      slug: "mocasin",
      subCatId: 1,
      catId: 1,
      description: "Comfortable mocasin shoes for a casual style.",
      hasFreeDelivery: true,
      currentPrice: 70000,
      originalPrice:100000,
      subCatName: "Shoes",
      images: [
        "/shoes/mocasin/1.jpg",
        "/shoes/mocasin/2.jpg",
        "/shoes/mocasin/3.jpg",
        "/shoes/mocasin/4.jpg",
        "/shoes/mocasin/5.jpg",
        "/shoes/mocasin/6.jpg",
        "/shoes/mocasin/7.jpg",
        "/shoes/mocasin/8.jpg",
        "/shoes/mocasin/9.jpg",
        "/shoes/mocasin/10.jpg",
        "/shoes/mocasin/12.jpg",
        "/shoes/mocasin/13.jpg",
        "/shoes/mocasin/14.jpg",
        "/shoes/mocasin/15.jpg",
        "/shoes/mocasin/16.jpg",
        "/shoes/mocasin/17.jpg",
        "/shoes/mocasin/18.jpg",
        "/shoes/mocasin/19.jpg",
        "/shoes/mocasin/21.jpg",
      ],
    },
    {
      id: 3,
      title: "Gentle Shoes",
      image: "/shoes/gentle/22.jpg",
      slug: "gentle-shoes",
      subCatId: 1,
      catId: 1,
      description: "Elegant gentle shoes for a formal look.",
      hasFreeDelivery: true,
      currentPrice: 140000,
      originalPrice: 180000,
      subCatName: "Shoes",
      images: [
        "/shoes/gentle/1.jpg",
        "/shoes/gentle/2.jpg",
        "/shoes/gentle/3.jpg",
        "/shoes/gentle/4.jpg",
        "/shoes/gentle/5.jpg",
        "/shoes/gentle/6.jpg",
        "/shoes/gentle/7.jpg",
        "/shoes/gentle/8.jpg",
        "/shoes/gentle/9.jpg",
        "/shoes/gentle/10.jpg",
        "/shoes/gentle/12.jpg",
        "/shoes/gentle/13.jpg",
        "/shoes/gentle/14.jpg",
        "/shoes/gentle/15.jpg",
        "/shoes/gentle/16.jpg",
        "/shoes/gentle/17.jpg",
        "/shoes/gentle/18.jpg",
        "/shoes/gentle/19.jpg",
        "/shoes/gentle/21.jpg",
      ],
    },
    {
      id: 4,
      title: "Boots",
      image: "/shoes/boots/11.jpg",
      slug: "boots",
      subCatId: 1,
      catId: 1,
      description: "Durable boots for outdoor adventures.",
      hasFreeDelivery: true,
      currentPrice: 160000,
      originalPrice: 200000,
      subCatName: "Shoes",
      images: [
        "/shoes/boots/1.jpg",
        "/shoes/boots/2.jpg",
        "/shoes/boots/3.jpg",
        "/shoes/boots/4.jpg",
        "/shoes/boots/5.jpg",
        "/shoes/boots/6.jpg",
        "/shoes/boots/7.jpg",
        "/shoes/boots/8.jpg",
        "/shoes/boots/9.jpg",
        "/shoes/boots/10.jpg",
        "/shoes/boots/12.jpg",
        "/shoes/boots/13.jpg",
        "/shoes/boots/14.jpg",
        "/shoes/boots/15.jpg",
        "/shoes/boots/16.jpg",
        "/shoes/boots/17.jpg",
        "/shoes/boots/18.jpg",
        "/shoes/boots/19.jpg",
        "/shoes/boots/21.jpg",
      ],
    },
    {
      id: 5,
      title: "Nike Sneakers",
      image: "/shoes/nike/4.jpg",
      slug: "nike-sneakers",
      subCatId: 1,
      catId: 1,
      description: "High-quality Nike sneakers for sports and style.",
      hasFreeDelivery: true,
      currentPrice: 130000,
      originalPrice: 180000,
      subCatName: "Shoes",
      images: [
        "/shoes/nike/1.jpg",
        "/shoes/nike/2.jpg",
        "/shoes/nike/3.jpg",
        "/shoes/nike/4.jpg",
        "/shoes/nike/5.jpg",
        "/shoes/nike/6.jpg",
        "/shoes/nike/7.jpg",
        "/shoes/nike/8.jpg",
        "/shoes/nike/9.jpg",
        "/shoes/nike/10.jpg",
        "/shoes/nike/12.jpg",
        "/shoes/nike/13.jpg",
        "/shoes/nike/14.jpg",
        "/shoes/nike/15.jpg",
        "/shoes/nike/16.jpg",
        "/shoes/nike/17.jpg",
        "/shoes/nike/18.jpg",
        "/shoes/nike/19.jpg",
        "/shoes/nike/21.jpg",
      ],
    },
    {
      id: 6,
      title: "Vans Sneaker",
      image: "/shoes/van/3.jpg",
      slug: "vans-sneaker",
      subCatId: 1,
      catId: 1,
      description: "Casual Vans sneakers for everyday comfort.",
      hasFreeDelivery: true,
      currentPrice: 70000,
      originalPrice: 100000,
      subCatName: "Shoes",
      images: [
        "/shoes/van/1.jpg",
        "/shoes/van/2.jpg",
        "/shoes/van/3.jpg",
        "/shoes/van/4.jpg",
        "/shoes/van/5.jpg",
        "/shoes/van/6.jpg",
        "/shoes/van/7.jpg",
        "/shoes/van/8.jpg",
        "/shoes/van/9.jpg",
        "/shoes/van/10.jpg",
        "/shoes/van/12.jpg",
        "/shoes/van/13.jpg",
        "/shoes/van/14.jpg",
        "/shoes/van/15.jpg",
        "/shoes/van/16.jpg",
        "/shoes/van/17.jpg",
        "/shoes/van/18.jpg",
        "/shoes/van/19.jpg",
        "/shoes/van/21.jpg",
      ],
    },
    {
      id: 7,
      title: " Sandals",
      image: "/shoes/sandles/24.jpg",
      slug: "stylish-sandals",
      subCatId: 1,
      catId: 1,
      description: "Fashionable sandals for a relaxed and stylish look.",
      hasFreeDelivery: true,
      currentPrice: 60000,
      originalPrice: 80000,
      subCatName: "Shoes",
      images: [
        "/shoes/sandles/1.jpg",
        "/shoes/sandles/2.jpg",
        "/shoes/sandles/3.jpg",
        "/shoes/sandles/4.jpg",
        "/shoes/sandles/5.jpg",
        "/shoes/sandles/6.jpg",
        "/shoes/sandles/7.jpg",
        "/shoes/sandles/8.jpg",
        "/shoes/sandles/9.jpg",
        "/shoes/sandles/10.jpg",
        "/shoes/sandles/12.jpg",
        "/shoes/sandles/13.jpg",
        "/shoes/sandles/14.jpg",
        "/shoes/sandles/15.jpg",
        "/shoes/sandles/16.jpg",
        "/shoes/sandles/17.jpg",
        "/shoes/sandles/18.jpg",
        "/shoes/sandles/19.jpg",
        "/shoes/sandles/21.jpg",
        "/shoes/sandles/22.jpg",
        "/shoes/sandles/23.jpg",
        "/shoes/sandles/24.jpg",
      ],
    },
    // PANTS
    {
      id: 8,
      title: "Stretcher Khaki Trouser - Navy Blue",
      image: "/pants/khaki/1.jpg",
      slug: "stretcher-khaki-trouser-navy-blue-generic",
      subCatId: 2,
      catId: 1,
      description:
        "Navy blue chinos (stretcher) khaki will look good on your body.Choose from a wide range of Unique products onkyaja store Ug Ug and enjoy convenient and secure online shopping, delivery, guaranteed products and competitive pricing. Grab this deal and more at unbeatable prices with doorstep delivery.",
      hasFreeDelivery: true,
      currentPrice: 43000,
      originalPrice: 55000,
      subCatName: "Pants",
      images: [
        "/pants/khaki/1.jpg",
        "/pants/khaki/2.jpg",
        "/pants/khaki/3.jpg",
        "/pants/khaki/4.jpg",
      ],
    },
    {
      id: 9,
      title: "2pcs / Set Men's Casual Trousers Straight Pants - Beige + Navy",
      image: "/pants/casual/1.jpg",
      slug: "fashion-2pcs-set-mens-casual-trousers-straight-pants-beige-navy",
      subCatId: 2,
      catId: 1,
      description: "Stylish navy blue gentle trousers for a sophisticated look.",
      hasFreeDelivery: true,
      currentPrice: 69000,
      originalPrice: 128000,
      subCatName: "Pants",
      images: [
        "/pants/casual/1.jpg",
        "/pants/casual/2.jpg",
        "/pants/casual/3.jpg",
      ],
    },
    {
      id: 10,
      title:
        "4 Pack of Men's Formal Trousers - Black,Grey,Coffee Brown & Navy Blue",
      image: "/pants/gentle/1.jpg",
      slug: "generic-4-pack-of-mens-formal-trousers-blackgreycoffee-brown-navy-blue",
      subCatId: 2,
      catId: 1,
      description:
        "4 Pack of Men's Formal Trousers - Multi ColorFinished with the best details, these pair of Formal Trousers is cut for a perfect fit and showcases nice pocket styling with a button fly and wide belt loops.",
      hasFreeDelivery: true,
      currentPrice: 160000,
      originalPrice: 175000,
      subCatName: "Pants",
      images: [
        "/pants/gentle/1.jpg",
        "/pants/gentle/3.jpg",
        "/pants/gentle/4.jpg",
        "/pants/gentle/5.jpg",
      ],
    },
  //SHIRTS
  {
    id: 11,
    title: "Long-sleeved Men's Shirt",
    image: "/shirts/long/1.jpg",
    slug: "fashion-long-sleeved-mens-shirt",
    subCatId: 3,
    catId: 1,
    description:
      "Elevate your style with our Long-sleeved Men's Shirt, a versatile wardrobe essential. Perfect for both formal and casual occasions.",
    hasFreeDelivery: true,
    currentPrice: 160000,
    originalPrice: 175000,
    subCatName: "Shirts",
    images: [
      "/shirts/long/1.jpg",
      "/shirts/long/2.jpg",
      "/shirts/long/3.jpg",
      "/shirts/long/4.jpg",
    ],
  },
  {
    id: 12,
    title: "Mens Short Sleeve Shirts",
    image: "/shirts/short/1.jpg",
    slug: "fashion-short-sleeved-mens-shirt",
    subCatId: 3,
    catId: 1,
    description:
      "Stay cool and stylish with our Men's Short Sleeve Shirts, perfect for warm-weather comfort. These shirts offer a blend of casual charm and timeless fashion, making them a versatile addition to your summer wardrobe",
    hasFreeDelivery: true,
    currentPrice: 160000,
    originalPrice: 175000,
    subCatName: "Shirts",
    images: [
      "/shirts/short/1.jpg",
      "/shirts/short/2.jpg",
      "/shirts/short/3.jpg",
    ],
  },
  //FRIDGES
  {
    id: 11,
    title: "8 Liters Double Door Refrigerator BCD 80999 - Silver",
    image: "/fridges/double-door.jpg",
    slug: "adh-98-liters-double-door-refrigerator-bcd",
    subCatId: 8,
    catId: 2,
    description:
      "Sleek and Beautiful: ADH Refrigerator is amazing! This fridge is perfect for a small office, dorm room, kitchen or playroom. The compressor cooling fridge will keep your drinks and food at a perfect temperature. With the built in freezer you can store your dinner, ice cream or other snacks!",
    hasFreeDelivery: true,
    currentPrice: 572500,
    originalPrice: 700000,
    subCatName: "Fridges",
    images: ["/fridges/double-door.jpg", "/fridges/double-door.jpg"],
  },
  {
    id: 12,
    title: "Hisense 195 Litres Single Door Silver Fridge - Silver",
    image: "/fridges/single-door.jpg",
    slug: "adh-98-liters-double-door-refrigerator-bcd",
    subCatId: 8,
    catId: 2,
    description:
      "With an optimized system design, enjoy a quieter life with low noise operation from your Hisense Refrigerator RR120DAGS. This product has a removable multiple-sealed door that can effectively isolate external heat and is also easy to clean. This product also has a multi-air flow system that distributes cold air evenly at each corner so that food quickly reaches the ideal storage temperature.",
    hasFreeDelivery: true,
    currentPrice: 802500,
    originalPrice: 1300000,
    subCatName: "Fridges",
    images: ["tshirt1.jpg", "tshirt2.jpg"],
  },
  //Tvs
  {
    id: 13,
    title: "Aiwa 32 inch HD Digital TV",
    image: "/awia/aiwatv1.jpg",
    slug: "aiwa-32-inch-hd-digital-tv",
    subCatId: 9,
    catId: 2,
    description:
      "Experience high-definition entertainment with the Aiwa 32 inch HD Digital TV. This TV features a crisp and clear display, perfect for your favorite shows and movies. With built-in digital capabilities, you can enjoy a wide range of channels without the need for an external set-top box. Grab this deal now!",
    hasFreeDelivery: true,
    currentPrice: 288900,
    originalPrice: 490000,
    subCatName: "Televisions",
    images: ["/awia/aiwatv1.jpg", "/awia/aiwa2.jpg"],
  },
  {
    id: 14,
    title: "Hisense 32 inch HDR LED TV",
    image: "/hi/hi.jpg",
    slug: "hisense-32-inch-hdr-led-tv",
    subCatId: 9,
    catId: 2,
    description:
      "Upgrade your home entertainment with the Hisense 32 inch HDR LED TV. Experience stunning high dynamic range visuals and immerse yourself in your favorite content. With a sleek design and advanced features, this TV is a great addition to your living space.",
    hasFreeDelivery: true,
    currentPrice: 557000,
    originalPrice: 700000,
    subCatName: "Televisions",
    images: ["/hi/hi.jpg", "/hi/hi2.jpg"],
  },
  {
    id: 15,
    title: "DURBYMAX 32 inch Semi-Smart TV",
    image: "/durby/durby1.jpg",
    slug: "durbymax-32-inch-semi-smart-tv",
    subCatId: 9,
    catId: 2,
    description:
      "Get the best of both worlds with the DURBYMAX 32 inch Semi-Smart TV. Enjoy high-quality entertainment with smart features that allow you to stream your favorite content. This TV offers a fantastic viewing experience at an affordable price.",
    hasFreeDelivery: true,
    currentPrice: 335000,
    originalPrice: 500000,
    subCatName: "Televisions",
    images: ["/durby/durby1.jpg", "/durby/durby2.jpg", "/durby/durby3.jpg"],
  },
  {
    id: 16,
    title: "Sky 40 inch Android Smart HDR Digital TV",
    image: "/andriod/andriod.jpg",
    slug: "sky-40-inch-android-smart-hdr-digital-tv",
    subCatId: 9,
    catId: 2,
    description:
      "Elevate your viewing experience with the Sky 40 inch Android Smart HDR Digital TV. This TV features a stunning HDR display and runs on the Android operating system, giving you access to a world of entertainment and apps. Enjoy crystal-clear visuals and smart functionality at an unbeatable price.",
    hasFreeDelivery: true,
    currentPrice: 479000,
    originalPrice: 700000,
    subCatName: "Televisions",
    images: ["/andriod/andriod.jpg", "/andriod/andriod2.jpg"],
  },
  //woofers
  {
    id: 17,
    title: "ALIPU 3.1 Bluetooth Multimedia Strong Bass Subwoofer - Black",
    image: "/hoofer/hoofer1.jpg",
    slug: "alipu-3.1-bluetooth-multimedia-subwoofer",
    subCatId: 10,
    catId: 2,
    description:
      "Experience powerful sound with the ALIPU 3.1 Bluetooth Multimedia Subwoofer. With strong bass and wireless Bluetooth connectivity, this subwoofer takes your audio experience to the next level. Perfect for music lovers and movie enthusiasts.",
    hasFreeDelivery: true,
    currentPrice: 154000,
    originalPrice: 190000,
    subCatName: "Speakers",
    images: ["/hoofer/hoofer1.jpg", "/hoofer/hoofer2.jpg"],
  },
  {
    id: 18,
    title: "Djack 3.1 HiFi Multimedia Bluetooth AC/DC Speaker",
    image: "/hoofer/hoofer3.jpg",
    slug: "djack-3.1-hifi-multimedia-speaker",
    subCatId: 10,
    catId: 2,
    description:
      "Upgrade your audio experience with the Djack 3.1 HiFi Multimedia Bluetooth Speaker. This speaker offers powerful sound with HiFi quality and Bluetooth connectivity. Whether you're at home or on the go, enjoy your favorite music with clarity.",
    hasFreeDelivery: true,
    currentPrice: 139000,
    originalPrice: 150000,
    subCatName: "Speakers",
    images: ["/hoofer/hoofer3.jpg", "/hoofer/hoofer3.jpg"],
  },
  {
    id: 19,
    title: "Bluetooth Home Theatre System (Silver)",
    image: "/homethe/homethe1.jpg",
    slug: "bluetooth-home-theatre-silver",
    subCatId: 10,
    catId: 2,
    description:
      "Transform your home entertainment with the Bluetooth Home Theatre System in Silver. This system delivers immersive sound and connects wirelessly via Bluetooth. Enjoy movie nights and music sessions like never before.",
    hasFreeDelivery: true,
    currentPrice: 138000,
    originalPrice: 199000,
    subCatName: "Speakers",
    images: ["/homethe/homethe1.jpg", "/homethe/homethe2.jpg"],
  },
  {
    id: 20,
    title: "8 Inch Subwoofer Home Theatre Sound System (Extra)",
    image: "/homethre4.jpg",
    slug: "8-inch-subwoofer-home-theatre-sound-system",
    subCatId: 10,
    catId: 2,
    description:
      "Experience deep, rich bass with the 8 Inch Subwoofer Home Theatre Sound System. This extra-powerful subwoofer enhances your home theater experience, making movies and music come alive. Get ready for a cinematic journey at home!",
    hasFreeDelivery: true,
    currentPrice: 240000,
    originalPrice: 250000,
    subCatName: "Speakers",
    images: ["/homethre4.jpg", "/homethre4.jpg"],
  },
  //samsung
  {
    id: 21,
    title: "Samsung Galaxy A14 4G (6GB RAM, 128GB)",
    image: "/samsung/samsingA14.jpg",
    slug: "samsung-galaxy-a14-4g-6gb-128gb",
    subCatId: 11,
    catId: 3,
    description:
      "Get the Samsung Galaxy A14 4G with 6GB RAM and 128GB of storage. This smartphone offers powerful performance and ample storage for all your needs. With the trusted Samsung quality, stay connected and productive on the go.",
    hasFreeDelivery: true,
    currentPrice: 620000,
    originalPrice: 640000,
    subCatName: "Smartphones",
    images: ["/samsung/samsingA14.jpg", "/samsung/samsung2.jpg"],
  },
  {
    id: 22,
    title: "Samsung Galaxy Note20 Ultra 4G (8GB RAM, 128GB RAM)",
    image: "/samsungnote20.jpg",
    slug: "samsung-galaxy-note20-ultra-4g-8gb-128gb",
    subCatId: 11,
    catId: 3,
    description:
      "Experience the power of the Samsung Galaxy Note20 Ultra 4G with 8GB RAM and 128GB storage. This flagship smartphone delivers exceptional performance and cutting-edge features. Capture moments, stay organized, and do more with this premium device.",
    hasFreeDelivery: true,
    currentPrice: 1990000,
    originalPrice: 2100000,
    subCatName: "Smartphones",
    images: ["/samsungnote20.jpg", "/samsungnote20.jpg"],
  },
  {
    id: 23,
    title: "Samsung S20+ (128GB RAM)",
    image: "/samsung/samsungs20.jpg",
    slug: "samsung-s20-plus-128gb-ram",
    subCatId: 11,
    catId: 3,
    description:
      "Upgrade to the Samsung S20+ with 128GB of RAM. This smartphone offers high-end performance and an exceptional camera system. Stay connected, take stunning photos, and enjoy a premium mobile experience.",
    hasFreeDelivery: true,
    currentPrice: 1700000,
    originalPrice: 3000000,
    subCatName: "Smartphones",
    images: ["/samsung/samsungs20.jpg", "/samsung/samsungs201.jpg"],
  },
  {
    id: 24,
    title: "Samsung S8 (4GB RAM, 64GB)",
    image: "/samsung/samsungs8.jpg",
    slug: "samsung-s8-4gb-64gb",
    subCatId: 11,
    catId: 3,
    description:
      "Get the Samsung S8 with 4GB RAM and 64GB of storage. This classic smartphone offers a balance of performance and design. Stay connected and enjoy the features you love at an affordable price.",
    hasFreeDelivery: true,
    currentPrice: 745000,
    originalPrice: 1300000,
    subCatName: "Smartphones",
    images: ["/samsung/samsungs8.jpg", "/samsung/samsungs82.jpg"],
  },
  //iphone
  {
    id: 25,
    title: "iPhone 14 Pro (6GB, 256GB)",
    image: "/iphone/iphone.jpg",
    slug: "iphone-14-pro-6gb-256gb",
    subCatId: 12,
    catId: 3,
    description:
      "Experience the power of the iPhone 14 Pro with 6GB of RAM and 256GB storage. This flagship smartphone offers a stunning camera system, lightning-fast performance, and a sleek design. Capture, create, and connect like never before.",
    hasFreeDelivery: true,
    currentPrice: 4200000,
    originalPrice: 5200000,
    subCatName: "Smartphones",
    images: ["/iphone/iphone.jpg", "/iphone/iphone.jpg"],
  },
  {
    id: 26,
    title: "iPhone 13 Pro Max (6GB, 256GB)",
    image: "/iphone/iphone13.jpg",
    slug: "iphone-13-pro-max-6gb-256gb",
    subCatId: 12,
    catId: 3,
    description:
      "Get the iPhone 13 Pro Max with 6GB of RAM and 256GB storage. This powerful iPhone offers a large display, advanced camera capabilities, and impressive performance. Stay productive and entertained with this premium device.",
    hasFreeDelivery: true,
    currentPrice: 3200000,
    originalPrice: 4200000,
    subCatName: "Smartphones",
    images: ["/iphone/iphone13.jpg", "/iphone/iphone132.jpg"],
  },
  {
    id: 27,
    title: "Apple S7 Plus (32GB)",
    image: "/iphone/samsungs7.jpg",
    slug: "apple-s7-plus-32gb",
    subCatId: 12,
    catId: 3,
    description:
      "Experience the Apple S7 Plus with 32GB of storage. This tablet offers a beautiful display, great performance, and access to a wide range of apps. It's perfect for work and entertainment on the go.",
    hasFreeDelivery: true,
    currentPrice: 1200000,
    originalPrice: 2000000,
    subCatName: "Mobile phone",
    images: ["/iphone/samsungs7.jpg", "/iphone/samsungs7.jpg"],
  },
  {
    id: 28,
    title: "Apple 15 (6GB, 128GB)",
    image: "/iphone/iphone15.jpg",
    slug: "apple-15-6gb-128gb",
    subCatId: 12,
    catId: 3,
    description:
      "Get the Apple 15 with 6GB of RAM and 128GB storage. This iPhone offers a balance of performance and style. Stay connected and enjoy the features you love at a great price.",
    hasFreeDelivery: true,
    currentPrice: 3900000,
    originalPrice: 5000000,
    subCatName: "Smartphones",
    images: ["/iphone/iphone15.jpg", "/iphone/iphone152.jpg"],
  },
  //tecno
  {
    id: 29,
    title: "Tecno Camon 20 (8GB, 256GB)",
    image: "/tecno/tecno1.jpg",
    slug: "tecno-camon-20-8gb-256gb",
    subCatId: 13,
    catId: 3,
    description:
      "Get the Tecno Camon 20 with 8GB of RAM and 256GB storage. This smartphone offers a large display, impressive camera features, and ample storage for your apps and media. Capture moments and stay connected with this Tecno device.",
    hasFreeDelivery: true,
    currentPrice: 760000,
    originalPrice: 820000,
    subCatName: "Smartphones",
    images: ["/tecno/tecno1.jpg", "/tecno/tecno2.jpg"],
  },
  {
    id: 30,
    title: "Tecno Spark 10 C (4GB, 128GB)",
    image: "/tecno/tecno.jpg",
    slug: "tecno-spark-10-c-4gb-128gb",
    subCatId: 13,
    catId: 3,
    description:
      "Upgrade to the Tecno Spark 10 C with 4GB of RAM and 128GB storage. This smartphone offers a balance of performance and value. Stay productive and entertained with this Tecno device.",
    hasFreeDelivery: true,
    currentPrice: 420000,
    originalPrice: 700000,
    subCatName: "Smartphones",
    images: ["/tecno/tecno.jpg", "/tecno/tecno.jpg"],
  },
  //nokia
  {
    id: 31,
    title: "Nokia 105 Dual SIM (4MB, 4MB)",
    image: "/nokia/nokia.jpg",
    slug: "nokia-105-dual-sim-4mb-4mb",
    subCatId: 14,
    catId: 3,
    description:
      "Get the Nokia 105 Dual SIM with 4MB of storage. This basic mobile phone is perfect for those who need a reliable and easy-to-use device for calls and text messages. Stay connected with Nokia quality.",
    hasFreeDelivery: true,
    currentPrice: 70000,
    originalPrice: 100000,
    subCatName: "Mobile Phones",
    images: ["/nokia/nokia.jpg", "/nokia/nokia.jpg"],
  },
  {
    id: 32,
    title: "Nokia 5310 Dual SIM (16MB)",
    image: "/nokia/nokia2.jpg",
    slug: "nokia-5310-dual-sim-16mb",
    subCatId: 14,
    catId: 3,
    description:
      "Get the Nokia 5310 Dual SIM with 16MB of storage. This classic mobile phone combines modern features with a nostalgic design. Enjoy your favorite music and stay connected with this Nokia device.",
    hasFreeDelivery: true,
    currentPrice: 120000,
    originalPrice: 180000,
    subCatName: "Mobile Phones",
    images: ["phone1.jpg", "phone2.jpg"],
  },
  //HP
  {
    id: 33,
    title: "HP Pavilion Aero (16GB)",
    image: "/hp/hp.jpg",
    slug: "hp-pavilion-aero-16gb",
    subCatId: 15,
    catId: 4,
    description:
      "Experience powerful computing with the HP Pavilion Aero laptop featuring 16GB of RAM. This laptop is designed for performance and portability, making it ideal for work and entertainment. Get it now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 1500000,
    originalPrice: 3000000,
    subCatName: "Laptops",
    images: ["/hp/hp2.jpg", "/hp/hp3.jpg", "/hp/hp.jpg"],
  },
  {
    id: 34,
    title: "HP EliteBook (i5, 16GB)",
    image: "/hp/elite.jpg",
    slug: "hp-elitebook-i5-16gb",
    subCatId: 15,
    catId: 4,
    description:
      "Upgrade your computing experience with the HP EliteBook featuring an i5 processor and 16GB of RAM. This laptop offers premium performance and security features, making it perfect for business and productivity.",
    hasFreeDelivery: true,
    currentPrice: 190000,
    originalPrice: 24000,
    subCatName: "Laptops",
    images: ["/hp/elite.jpg", "/hp/elite2.jpg"],
  },
  {
    id: 35,
    title: "HP RePublisher 14 (i5, 8GB)",
    image: "/hp/hp4.jpg",
    slug: "hp-republisher-14-i5-8gb",
    subCatId: 15,
    catId: 4,
    description:
      "Get the HP RePublisher 14 laptop with an i5 processor and 8GB of RAM. This laptop offers a balance of performance and value, making it great for a variety of tasks. Get yours at a special price!",
    hasFreeDelivery: true,
    currentPrice: 850000,
    originalPrice: 1500000,
    subCatName: "Laptops",
    images: ["/hp/hp4.jpg", "/hp/hp5.jpg"],
  },
  {
    id: 36,
    title: "HP 17 Refurbised 840 G3  Dual (8GB)",
    image: "/hp/hp9.jpg",
    slug: "hp-15-pentium-dual-4gb",
    subCatId: 15,
    catId: 4,
    description:
      "Get the HP 15 Pentium Dual laptop with 4GB of RAM. This laptop offers essential computing features at an affordable price. It's perfect for everyday tasks and on-the-go computing.",
    hasFreeDelivery: true,
    currentPrice: 1100000,
    originalPrice: 800000,
    subCatName: "Laptops",
    images: ["/hp/hp9.jpg", "/hp/hp10.jpg"],
  },

  //Dell
  {
    id: 37,
    title: "DELL Latitude 3340 (Intel Core i3, 4GB)",
    image: "/dell/dell1.jpg",
    slug: "dell-latitude-3340-i3-4gb",
    subCatId: 16,
    catId: 4,
    description:
      "Get the DELL Latitude 3340 laptop with an Intel Core i3 processor and 4GB of RAM. This laptop is designed for performance and reliability, making it perfect for everyday computing. Grab it at a special price!",
    hasFreeDelivery: true,
    currentPrice: 600000,
    originalPrice: 1080000,
    subCatName: "Laptops",
    images: ["/dell/dell1.jpg", "/dell/dell2.jpg"],
  },
  {
    id: 38,
    title: "DELL Regishushed Latitude E7400 (8GB, 256GB)",
    image: "/dell/dell3.jpg",
    slug: "dell-regishushed-latitude-e6000-2gb-250gb",
    subCatId: 16,
    catId: 4,
    description:
      "Upgrade your computing experience with the DELL Regishushed Latitude E6000 laptop featuring 2GB of RAM and a 250GB hard drive. This laptop offers a balance of performance and storage for your needs. Get it now at a great price!",
    hasFreeDelivery: true,
    currentPrice: 739000,
    originalPrice: 1040000,
    subCatName: "Laptops",
    images: ["laptop1.jpg", "laptop2.jpg"],
  },
  {
    id: 39,
    title: "DELL Regishushed (4GB RAM, 258GB i5, 8GB)",
    image: "/dell/dell4.jpg",
    slug: "dell-regishushed-4gb-258gb-i5-8gb",
    subCatId: 16,
    catId: 4,
    description:
      "Get the DELL Regishushed laptop with 4GB of RAM and 258GB storage, featuring an Intel Core i5 processor and 8GB RAM. This laptop offers performance and ample storage for a variety of tasks. Don't miss out on this deal!",
    hasFreeDelivery: true,
    currentPrice: 819000,
    originalPrice: 1200000,
    subCatName: "Laptops",
    images: ["laptop1.jpg", "laptop2.jpg"],
  },
  //Lenovo
  {
    id: 40,
    title: "Lenovo Refurbished X1 YOGA (8GB, SSD 256GB, i5)",
    image: "/lenovo/lenovo.jpg",
    slug: "lenovo-refurbished-x1-yoga-8gb-ssd-256gb-i5",
    subCatId: 17,
    catId: 4,
    description:
      "Upgrade to the Lenovo Refurbished X1 YOGA laptop with 8GB of RAM, a 256GB SSD, and an Intel Core i5 processor. This laptop offers premium performance and a sleek design. Get it at a great price!",
    hasFreeDelivery: true,
    currentPrice: 1000000,
    originalPrice: 1200000,
    subCatName: "Laptops",
    images: ["/lenovo/lenovo.jpg", "/lenovo/lenovo.jpg"],
  },
  {
    id: 41,
    title: "Lenovo ThinkPad T470 Business Laptop",
    image: "/lenovo/lenovo2.jpg",
    slug: "lenovo-thinkpad-t470-business-laptop",
    subCatId: 17,
    catId: 4,
    description:
      "Enhance your business productivity with the Lenovo ThinkPad T470 business laptop. This laptop offers powerful performance and reliable features for your work tasks. Invest in your business with this Lenovo device.",
    hasFreeDelivery: true,
    currentPrice: 1500000,
    originalPrice: 1700000,
    subCatName: "Laptops",
    images: ["/lenovo/lenovo2.jpg", "/lenovo/lenovo2.jpg"],
  },
  //WATCHES FOR MEN
  {
    id: 42,
    title: "Chicmi Y13 Multifunction Smart Watch with Step Counter and Touch",
    image: "/watches/chimi.jpg",
    slug: "chicmi-y13-multifunction-smart-watch",
    subCatId: 18,
    catId: 5,
    description:
      "Stay active and connected with the Chicmi Y13 smart watch. This multifunctional smart watch features a step counter and a touch screen for easy use. Get it now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 22000,
    originalPrice: 40000,
    subCatName: "Smart Watches",
    images: [
      "/watches/chimi.jpg",
      "/watches/chimi2.jpg",
      "/watches/chimi3.jpg",
    ],
  },
  {
    id: 43,
    title: "Geneva Luxury Brand Watches (Famous)",
    image: "/watches/geneva.jpg",
    slug: "geneva-luxury-brand-watches-famous",
    subCatId: 18,
    catId: 5,
    description:
      "Elevate your style with the Geneva Luxury Brand Watches. These famous watches offer a touch of luxury and elegance. They make the perfect accessory for any occasion.",
    hasFreeDelivery: true,
    currentPrice: 22000,
    originalPrice: 39900,
    subCatName: "Watches",
    images: ["/watches/geneva.jpg", "/watches/geneva2.jpg"],
  },
  {
    id: 44,
    title: "Geneva Men Watches (Quartz Watch, Slim)",
    image: "/watches/watch8.jpg",
    slug: "geneva-men-watches-quartz-watch-slim",
    subCatId: 18,
    catId: 5,
    description:
      "Enhance your style with Geneva Men Watches featuring a slim design and precise quartz movement. These watches offer a timeless and elegant look for men with great taste.",
    hasFreeDelivery: true,
    currentPrice: 22000,
    originalPrice: 30900,
    subCatName: "Watches",
    images: ["/watches/watch8.jpg", "/watches/watch8.jpg"],
  },
  {
    id: 45,
    title: "Full Touch Screen Smart Watch",
    image: "/watches/watch10.jpg",
    slug: "full-touch-screen-smart-watch",
    subCatId: 18,
    catId: 5,
    description:
      "Experience the future of smart wearables with the Full Touch Screen Smart Watch. This watch offers a full touch screen for easy navigation and a wide range of features. Get it at a great price!",
    hasFreeDelivery: true,
    currentPrice: 27000,
    originalPrice: 50000,
    subCatName: "Smart Watches",
    images: ["/watches/watch10.jpg", "/watches/watch10.jpg"],
  },
  //WATCHES FOR WOMEN
  {
    id: 46,
    title: "J&W Wristwatch with Royal Rose Gold",
    image: "/watches/woman1.jpg",
    slug: "jw-wristwatch-royal-rose-gold",
    subCatId: 19,
    catId: 5,
    description:
      "Elevate your style with the J&W wristwatch featuring a royal rose gold design. This elegant wristwatch adds a touch of luxury to any outfit. Get it now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 18000,
    originalPrice: 30000,
    subCatName: "Wristwatches",
    images: ["/watches/woman2.jpg", "/watches/woman3.jpg"],
  },
  {
    id: 47,
    title: "4pcs Women Watch Necklace Earrings Set",
    image: "/watches/woman4.jpg",
    slug: "4pcs-women-watch-necklace-earrings-set",
    subCatId: 19,
    catId: 5,
    description:
      "Complete your look with the 4pcs Women Watch Necklace Earrings Set. This set includes a stylish watch, necklace, and earrings, making it a perfect accessory combination for women.",
    hasFreeDelivery: true,
    currentPrice: 31000,
    originalPrice: 50000,
    subCatName: "Jewelry Sets",
    images: ["/watches/woman4.jpg", "/watches/woman5.jpg"],
  },
  {
    id: 48,
    title: "Geneva Women Watches (Quartz Watch, Slim)",
    image: "/watches/womangeneva1.jpg",
    slug: "geneva-women-watches-quartz-watch-slim",
    subCatId: 19,
    catId: 5,
    description:
      "Enhance your style with Geneva Women Watches featuring a slim design and precise quartz movement. These watches offer a timeless and elegant look for women with great taste.",
    hasFreeDelivery: true,
    currentPrice: 40000,
    originalPrice: 50900,
    subCatName: "Wristwatches",
    images: ["/watches/womangeneva1.jpg", "/watches/womangeneva2.jpg"],
  },
  {
    id: 49,
    title:
      "Luxury Diamond Butterfly Bracelet For Apple Watch Band 8 7 SE 6 5 41mm 45mm 42mm 44 40mm 38mm Women Gold Wristband Lady Strap",
    image: "/watches/woman12.jpg",
    slug: "women-pale-wrist-watch-lady-fashion",
    subCatId: 19,
    catId: 5,
    description:
      "Add a touch of fashion to your wrist with the Women Pale Wrist Watch. This stylish watch is perfect for women who love to express their fashion sense. Get it at a great price!",
    hasFreeDelivery: true,
    currentPrice: 87400,
    originalPrice: 150000,
    subCatName: "Wristwatches",
    images: ["/watches/woman12.jpg", "/watches/woman12.jpg"],
  },
  //digital watches
  {
    id: 50,
    title: "Smart Watch Camera Waterproof SIM Card Wrist Watch",
    image: "/digital/digital1.jpg",
    slug: "smart-watch-camera-waterproof-sim-card-wrist-watch",
    subCatId: 20,
    catId: 6,
    description:
      "Experience the future of wrist wearables with the Smart Watch Camera. This waterproof wrist watch features a camera and SIM card support. Stay connected and capture moments with this innovative smart watch.",
    hasFreeDelivery: true,
    currentPrice: 35000,
    originalPrice: 50000,
    subCatName: "Smart Watches",
    images: ["/digital/digital1.jpg", "/digital/digital2.jpg"],
  },
  {
    id: 51,
    title: "LED Silicone Wrist Watches (Brands)",
    image: "/digital/digital3.jpg",
    slug: "led-silicone-wrist-watches-brands",
    subCatId: 20,
    catId: 6,
    description:
      "Add a pop of color to your style with LED Silicone Wrist Watches. These branded watches feature LED lights for a unique and eye-catching look. Get them now at a great price!",
    hasFreeDelivery: true,
    currentPrice: 9000,
    originalPrice: 20000,
    subCatName: "Wrist Watches",
    images: ["/digital/digital3.jpg", "/digital/digital3.jpg"],
  },
  {
    id: 52,
    title: "Wrista Smart Watch (Brands, Bracelet)",
    image: "/digital/digital4.jpg",
    slug: "wrista-smart-watch-brands-bracelet",
    subCatId: 20,
    catId: 6,
    description:
      "Elevate your wristwear with the Wrista Smart Watch featuring branded design and a stylish bracelet strap. This smart watch offers a perfect blend of fashion and functionality.",
    hasFreeDelivery: true,
    currentPrice: 16000,
    originalPrice: 19000,
    subCatName: "Smart Watches",
    images: ["/digital/digital4.jpg", "/digital/digital5.jpg"],
  },
  {
    id: 53,
    title: "Wrista Smart Watch (Brands, Bracelet Strap)",
    image: "/digital/digital6.jpg",
    slug: "wrista-smart-watch-brands-bracelet-strap",
    subCatId: 20,
    catId: 6,
    description:
      "Elevate your wristwear with the Wrista Smart Watch featuring branded design and a stylish bracelet strap. This smart watch offers a perfect blend of fashion and functionality.",
    hasFreeDelivery: true,
    currentPrice: 19000,
    originalPrice: 18000,
    subCatName: "Smart Watches",
    images: ["/digital/digital6.jpg", "/digital/digital7.jpg"],
  },
  //blankets
  {
    id: 54,
    title: "Double Face Soft Fleece",
    image: "/blanckets/blancket.jpg",
    slug: "double-face-soft-fleece",
    subCatId: 21,
    catId: 7,
    description:
      "Stay warm and cozy with the Double Face Soft Fleece blanket. This soft and plush fleece blanket features a double-face design for added warmth. Get it now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 80000,
    originalPrice: 90000,
    subCatName: "Fleece Blankets",
    images: ["/blanckets/blancket1.jpg", "/blanckets/blancket2.jpg"],
  },
  {
    id: 55,
    title: "Fleece Woolen Soft Blanket",
    image: "/blanckets/blancket1.jpg",
    slug: "fleece-woolen-soft-blanket",
    subCatId: 21,
    catId: 7,
    description:
      "Wrap yourself in comfort with the Fleece Woolen Soft Blanket. This soft and warm fleece blanket is perfect for cozying up on cold days. Don't miss out on this great deal!",
    hasFreeDelivery: true,
    currentPrice: 95000,
    originalPrice: 100000,
    subCatName: "Fleece Blankets",
    images: ["/blanckets/blancket1.jpg", "/blanckets/blancket1.jpg"],
  },
  {
    id: 56,
    title: "Fleece Woolen Soft Blanket (Gray)",
    image: "/blanckets/blancket6.jpg",
    slug: "fleece-woolen-soft-blanket-gray",
    subCatId: 21,
    catId: 7,
    description:
      "Add a touch of elegance to your bedding with the Fleece Woolen Soft Blanket in gray. This soft fleece blanket is perfect for staying warm in style. Get it now at a great price!",
    hasFreeDelivery: true,
    currentPrice: 110000,
    originalPrice: 150000,
    subCatName: "Fleece Blankets",
    images: ["/blanckets/blancket6.jpg", "/blanckets/blancket6.jpg"],
  },
  {
    id: 57,
    title: "Fleece Woolen Soft Blanket (Brown)",
    image: "/blanckets/blancket8.jpg",
    slug: "fleece-woolen-soft-blanket-brown",
    subCatId: 21,
    catId: 7,
    description:
      "Enjoy the warmth and comfort of the Fleece Woolen Soft Blanket in brown. This cozy fleece blanket is perfect for chilly evenings. Get it now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 150000,
    originalPrice: 190000,
    subCatName: "Fleece Blankets",
    images: ["/blanckets/blancket8.jpg", "/blanckets/blancket6.jpg"],
  },
  //Duvet
  {
    id: 58,
    title: "Duvet 5*6 4pc Set (1 Bedsheet, 2 Pillow Cases)",
    image: "/Duvet/duvet.jpg",
    slug: "duvet-5x6-4pc-set-1-bedsheet-2-pillow-cases",
    subCatId: 22,
    catId: 7,
    description:
      "Upgrade your bedding with this 4-piece duvet set. It includes a 5*6 duvet, 1 bedsheet, and 2 pillow cases for a complete and cozy look. Get it now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 98000,
    originalPrice: 150000,
    subCatName: "Duvet Sets",
    images: ["/Duvet/duvet.jpg", "/Duvet/duvet.jpg"],
  },
  {
    id: 59,
    title: "Duvet 5*6 4pc Set (1 Bedsheet, 2 Pillow Cases, Multi-Color)",
    image: "/Duvet/duvet2.jpg",
    slug: "duvet-5x6-4pc-set-1-bedsheet-2-pillow-cases-multi-color",
    subCatId: 22,
    catId: 7,
    description:
      "Add a pop of color to your bedroom with this multi-color 4-piece duvet set. It includes a 5*6 duvet, 1 bedsheet, and 2 pillow cases. Elevate your bedding style with this set!",
    hasFreeDelivery: true,
    currentPrice: 134000,
    originalPrice: 130000,
    subCatName: "Duvet Sets",
    images: ["/Duvet/duvet2.jpg", "/Duvet/duvet2.jpg"],
  },
  {
    id: 60,
    title: "Duvet 5*6 4pc Set (1 Bedsheet, 2 Pillow Cases, White and Blue)",
    image: "/Duvet/duvet3.jpg",
    slug: "duvet-5x6-4pc-set-1-bedsheet-2-pillow-cases-white-blue",
    subCatId: 22,
    catId: 7,
    description:
      "Achieve a fresh and soothing look with this white and blue 4-piece duvet set. It includes a 5*6 duvet, 1 bedsheet, and 2 pillow cases. Make your bedroom an oasis of relaxation.",
    hasFreeDelivery: true,
    currentPrice: 150000,
    originalPrice: 250000,
    subCatName: "Duvet Sets",
    images: ["/Duvet/duvet2.jpg", "/Duvet/duvet2.jpg"],
  },
  {
    id: 61,
    title: "Children Duvet 5*6 4pc Set (1 Bedsheet, 2 Pillow Cases)",
    image: "/Duvet/childrenD.jpg",
    slug: "children-duvet-5x6-4pc-set-1-bedsheet-2-pillow-cases",
    subCatId: 22,
    catId: 7,
    description:
      "Create a cozy and colorful space for your children with this 4-piece duvet set. It includes a 5*6 duvet, 1 bedsheet, and 2 pillow cases. Make bedtime fun and comfortable!",
    hasFreeDelivery: true,
    currentPrice: 140000,
    originalPrice: 190000,
    subCatName: "Duvet Sets",
    images: ["/Duvet/childrenD.jpg", "/Duvet/childrenD.jpg"],
  },
  //pillow cases
  {
    id: 62,
    title: "Big Fiber Pillows (Pair, 2pcs, White with Soft Print)",
    image: "/pillow/pillow.jpg",
    slug: "big-fiber-pillows-pair-white-soft-print",
    subCatId: 23,
    catId: 7,
    description:
      "Upgrade your sleep with these big fiber pillows. This pair of 2 super soft pillows features a white cover with a soft print. Get them now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 22000,
    originalPrice: 70000,
    subCatName: "Fiber Pillows",
    images: ["/pillow/pillow.jpg", "/pillow/pillow.jpg"],
  },
  {
    id: 63,
    title: "Fiber Pillows (Pair, 2pcs, White, Super Soft)",
    image: "/pillow/pillow2.jpg",
    slug: "fiber-pillows-pair-white-super-soft",
    subCatId: 23,
    catId: 7,
    description:
      "Indulge in the comfort of these super soft fiber pillows. This pair of 2 white pillows is designed for ultimate softness and support. Elevate your sleep with this pair!",
    hasFreeDelivery: true,
    currentPrice: 20000,
    originalPrice: 40000,
    subCatName: "Fiber Pillows",
    images: ["pillow.jpg", "pillow2.jpg"],
  },
  {
    id: 64,
    title: "U-Shape Travel Pillow",
    image: "/pillow/u.jpg",
    slug: "u-shape-travel-pillow",
    subCatId: 23,
    catId: 7,
    description:
      "Make your travel more comfortable with the U-Shape Travel Pillow. This pillow provides support for your neck and head during long journeys. Get it now at a great price!",
    hasFreeDelivery: true,
    currentPrice: 68000,
    originalPrice: 80000,
    subCatName: "Travel Pillows",
    images: ["/pillow/u.jpg", "/pillow/u2.jpg"],
  },
  {
    id: 65,
    title: "Netflix Is My Boyfriend Pillow",
    image: "/pillow/netflix.jpg",
    slug: "netflix-is-my-boyfriend-pillow",
    subCatId: 23,
    catId: 7,
    description:
      "Express your love for Netflix with this fun and cozy pillow. The 'Netflix Is My Boyfriend' pillow is perfect for movie nights. Get it at a great price and cuddle up with your favorite shows!",
    hasFreeDelivery: true,
    currentPrice: 39000,
    originalPrice: 42000,
    subCatName: "Decorative Pillows",
    images: ["/pillow/netflix.jpg", "/pillow/netflix.jpg"],
  },
  //back to school bags
  {
    id: 66,
    title: "Laptop Bags",
    image: "/laptopbag/laptop1.jpg",
    slug: "laptop-bags",
    subCatId: 24,
    catId: 8,
    description:
      "Protect your laptop in style with these laptop bags. They are designed to keep your laptop safe and secure during your daily commute or travel. Get one now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 75000,
    originalPrice: 90000,
    subCatName: "Laptop Bags",
    images: ["/laptopbag/laptop1.jpg", "/laptopbag/laptop1.jpg"],
  },
  {
    id: 67,
    title: "Fiber Unisex Laptop Bag (Back to School)",
    image: "/laptopbag/laptop2.jpg",
    slug: "fiber-unisex-laptop-bag-back-to-school",
    subCatId: 24,
    catId: 8,
    description:
      "Prepare for the school year with this fiber unisex laptop bag. It's perfect for students heading back to school. Stay organized and stylish with this bag at a great price!",
    hasFreeDelivery: true,
    currentPrice: 49000,
    originalPrice: 90000,
    subCatName: "Back to School Bags",
    images: ["/laptopbag/laptop2.jpg", "/laptopbag/laptop2.jpg"],
  },
  {
    id: 68,
    title: "Fashion School Bag (Pink, Back to School)",
    image: "/laptopbag/laptop4.jpg",
    slug: "fashion-school-bag-pink-back-to-school",
    subCatId: 24,
    catId: 8,
    description:
      "Get ready for school in style with this pink fashion school bag. It's the perfect back-to-school accessory for students who love a touch of fashion. Grab one at a great price!",
    hasFreeDelivery: true,
    currentPrice: 55000,
    originalPrice: 140000,
    subCatName: "Back to School Bags",
    images: ["/laptopbag/laptop4.jpg", "/laptopbag/laptop4.jpg"],
  },
  {
    id: 69,
    title: "Luxury Clothing Design Backpacks",
    image: "/laptopbag/laptop5.jpg",
    slug: "luxury-clothing-design-backpacks",
    subCatId: 24,
    catId: 8,
    description:
      "Elevate your fashion with these luxury clothing design backpacks. They are perfect for carrying your essentials in style. Get one of these premium backpacks at a great price!",
    hasFreeDelivery: true,
    currentPrice: 240000,
    originalPrice: 420000,
    subCatName: "Fashion Backpacks",
    images: ["/laptopbag/laptop5.jpg", "/laptopbag/laptop5.jpg"],
  },
  //hand bags
  {
    id: 70,
    title: "2 in 1 Ladies Hand Bags (Leather)",
    image: "/handbag/handbag1.jpg",
    slug: "2-in-1-ladies-hand-bags-leather",
    subCatId: 25,
    catId: 8,
    description:
      "Elevate your style with these 2 in 1 ladies handbags made of high-quality leather. This versatile set of handbags is perfect for various occasions. Get them now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 28000,
    originalPrice: 50000,
    subCatName: "Ladies Handbags",
    images: ["/handbag/handbag1.jpg", "/handbag/handbag2.jpg"],
  },
  {
    id: 71,
    title: "Women Cross Bag (Leather)",
    image: "/handbag/handbag3.jpg",
    slug: "women-cross-bag-leather",
    subCatId: 25,
    catId: 8,
    description:
      "Add a touch of elegance to your outfit with this women's cross bag made of luxurious leather. It's the perfect accessory for any fashion-forward woman. Get it now at a great price!",
    hasFreeDelivery: true,
    currentPrice: 28000,
    originalPrice: 40000,
    subCatName: "Ladies Handbags",
    images: ["/handbag/handbag3.jpg", "/handbag/handbag3.jpg"],
  },
  {
    id: 72,
    title: "Women Leather Shoulder Bag",
    image: "/handbag/sb.jpg",
    slug: "women-leather-shoulder-bag",
    subCatId: 25,
    catId: 8,
    description:
      "Carry your essentials in style with this women's leather shoulder bag. It offers both fashion and functionality, making it an ideal choice. Grab one at a special price!",
    hasFreeDelivery: true,
    currentPrice: 89000,
    originalPrice: 140000,
    subCatName: "Ladies Handbags",
    images: ["/handbag/sb.jpg", "/handbag/sb.jpg"],
  },
  {
    id: 73,
    title: "Women Quality Leather Bag (Pink)",
    image: "/handbag/sb2.jpg",
    slug: "women-quality-leather-bag-pink",
    subCatId: 25,
    catId: 8,
    description:
      "Make a fashion statement with this high-quality pink leather bag designed for women. It's a perfect blend of style and durability. Get it at a great price and in your favorite color!",
    hasFreeDelivery: true,
    currentPrice: 28000,
    originalPrice: 56000,
    subCatName: "Ladies Handbags",
    images: ["/handbag/sb2.jpg", "/handbag/sb2.jpg"],
  },
  //travell bags
  {
    id: 74,
    title: "Nappoyo Leather Tenge Travel Bag",
    image: "/handbag/travel1.jpg",
    slug: "nappoyo-leather-tenge-travel-bag",
    subCatId: 26,
    catId: 8,
    description:
      "Travel in style with the Nappoyo Leather Tenge Travel Bag. This leather travel bag is perfect for your trips and adventures. Get it now at a great price and elevate your travel experience!",
    hasFreeDelivery: true,
    currentPrice: 170000,
    originalPrice: 200000,
    subCatName: "Travel Bags",
    images: ["/handbag/travel1.jpg", "/handbag/travel1.jpg"],
  },
  {
    id: 75,
    title: "Travel and Gym Bags",
    image: "/handbag/travel2.jpg",
    slug: "travel-and-gym-bags",
    subCatId: 26,
    catId: 8,
    description:
      "Stay organized during your travels and gym sessions with these versatile travel and gym bags. They are designed to carry your essentials with ease. Get one now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 125000,
    originalPrice: 140000,
    subCatName: "Travel Bags",
    images: ["/handbag/travel2.jpg", "/handbag/travel3.jpg"],
  },
  {
    id: 76,
    title: "Sports Bag and Gym Bag",
    image: "/handbag/travel4.jpg",
    slug: "sports-bag-and-gym-bag",
    subCatId: 26,
    catId: 8,
    description:
      "Carry your sports gear and gym essentials in style with this sports and gym bag. It's designed for active individuals who want functionality and fashion. Grab it at a great price!",
    hasFreeDelivery: true,
    currentPrice: 108000,
    originalPrice: 140000,
    subCatName: "Travel Bags",
    images: ["/handbag/travel4.jpg", "/handbag/travel4.jpg"],
  },
  {
    id: 77,
    title: "Buudy Travel Bags (4 Wheel Spinner)",
    image: "/handbag/travel7.jpg",
    slug: "buudy-travel-bags-4-wheel-spinner",
    subCatId: 26,
    catId: 8,
    description:
      "Upgrade your travel experience with these Buudy travel bags featuring a 4-wheel spinner design. They offer convenience and style for your journeys. Get one at a special price!",
    hasFreeDelivery: true,
    currentPrice: 40000,
    originalPrice: 560000,
    subCatName: "Travel Bags",
    images: ["/handbag/travel7.jpg", "/handbag/travel7.jpg"],
  },
  //T shirts
  {
    id: 78,
    title: "Men's Office Polo Shirts (Casual)",
    image: "/poloshirts/polo1.jpg",
    slug: "mens-office-polo-shirts-casual",
    subCatId: 4,
    catId: 1,
    description:
      "Upgrade your casual office attire with these men's office polo shirts. They offer a comfortable and stylish look for your workdays. Get them now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 23000,
    originalPrice: 55000,
    subCatName: "Polo Shirts",
    images: [
      "/poloshirts/polo1.jpg",
      "/poloshirts/polo2.jpg",
      "/poloshirts/polo3.jpg",
    ],
  },
  {
    id: 79,
    title: "Men Vintage Graffiti Shirts (Hawaii)",
    image: "/vintage/vintage1.jpg",
    slug: "men-vintage-graffiti-shirts-hawaii",
    subCatId: 4,
    catId: 1,
    description:
      "Get a taste of vintage fashion with these men's vintage graffiti shirts in a Hawaii style. They are perfect for a unique and stylish look. Grab one now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 24000,
    originalPrice: 47000,
    subCatName: "Vintage Shirts",
    images: ["/vintage/vintage2.jpg", "/vintage/vintage3.jpg"],
  },
  {
    id: 80,
    title: "Men Vintage T-Shirts (Beach Floral)",
    image: "/floral/floral1.jpg",
    slug: "men-vintage-t-shirts-beach-floral",
    subCatId: 4,
    catId: 1,
    description:
      "Capture the essence of the beach with these men's vintage t-shirts featuring a beach floral design. They are perfect for a relaxed and trendy look. Get one now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 24000,
    originalPrice: 470000,
    subCatName: "Vintage Shirts",
    images: ["/floral/floral2.jpg", "/floral/floral3.jpg"],
  },
  {
    id: 81,
    title: "Men's Formal Shirts (Casual)",
    image: "/men/men1.jpg",
    slug: "mens-formal-shirts-casual",
    subCatId: 4,
    catId: 1,
    description:
      "Upgrade your casual formal wear with these men's formal shirts. They offer a comfortable and polished look for various occasions. Get them now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 21000,
    originalPrice: 31000,
    subCatName: "Formal Shirts",
    images: ["/men/men1.jpg", "/men/men2.jpg", "/men/men3.jpg"],
  },
  //jackets
  {
    id: 82,
    title: "Trend Stand Collar Biker Jacket",
    image: "/jacket/jacket.jpg",
    slug: "trend-stand-collar-biker-jacket",
    subCatId: 5,
    catId: 1,
    description:
      "Stay in style with the Trend Stand Collar Biker Jacket. This jacket offers a sleek and trendy look for your everyday wear. Get it now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 180000,
    originalPrice: 250000,
    subCatName: "Biker Jackets",
    images: ["/jacket/jacket.jpg", "/jacket/jacket2.jpg"],
  },
  {
    id: 83,
    title: "American Fashion Brand Jacket",
    image: "/leather/jacketleather1.jpg",
    slug: "american-fashion-brand-jacket",
    subCatId: 5,
    catId: 1,
    description:
      "Experience American fashion with this brand jacket. It's perfect for those who appreciate a touch of American style. Grab one now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 156000,
    originalPrice: 207000,
    subCatName: "Fashion Brand Jackets",
    images: [
      "/leather/jacketleather1.jpg",
      ,
      "/leather/jacketleather2.jpg",
      "/leather/jacketleather3.jpg",
    ],
  },
  {
    id: 84,
    title: "Men's Jackets (Casual, Big Size)",
    image: "/j.jpg",
    slug: "mens-jackets-casual-big-size",
    subCatId: 5,
    catId: 1,
    description:
      "Find the perfect fit with these men's casual jackets in big sizes. They offer both style and comfort. Get one now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 137000,
    originalPrice: 470000,
    subCatName: "Casual Jackets",
    images: ["/j.jpg", "/j.jpg"],
  },
  {
    id: 85,
    title: "American Fashion Brand BF Jacket",
    image: "/blackj/blackj.jpg",
    slug: "american-fashion-brand-bf-jacket",
    subCatId: 5,
    catId: 1,
    description:
      "Elevate your style with this American fashion brand BF jacket. It's a blend of fashion and comfort, making it an ideal choice. Get it now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 150000,
    originalPrice: 211000,
    subCatName: "Fashion Brand Jackets",
    images: ["/blackj/blackj.jpg", "/blackj/blackj2.jpg"],
  },
  //sweaters
  {
    id: 86,
    title: "Classic Woodie Jumpers (Grey)",
    image: "/woodie/woodie1.jpg",
    slug: "classic-woodie-jumpers-grey",
    subCatId: 6,
    catId: 1,
    description:
      "Stay warm and stylish with the Classic Woodie Jumpers in grey. These jumpers are perfect for a classic and cozy look. Get them now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 33000,
    originalPrice: 55000,
    subCatName: "Woodie Jumpers",
    images: ["/woodie/woodie1.jpg", "/woodie/woodie2.jpg"],
  },
  {
    id: 87,
    title: "Men Wooded Sweater",
    image: "/menwoodie/menwoodie1.jpg",
    slug: "men-wooded-sweater",
    subCatId: 6,
    catId: 1,
    description:
      "Elevate your fashion with this men's wooded sweater. It's a perfect choice for staying warm and stylish. Get one now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 70000,
    originalPrice: 107000,
    subCatName: "Wooded Sweaters",
    images: ["/menwoodie/menwoodie2.jpg", "/menwoodie/menwoodie3.jpg"],
  },
  {
    id: 88,
    title: "Wool Fashion Slim Fit Sweater",
    image: "/slim.jpg",
    slug: "wool-fashion-slim-fit-sweater",
    subCatId: 6,
    catId: 1,
    description:
      "Achieve a slim and fashionable look with this wool fashion slim fit sweater. It's designed for style and comfort. Grab one now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 39000,
    originalPrice: 47000,
    subCatName: "Slim Fit Sweaters",
    images: ["/slim.jpg", "/slim.jpg"],
  },
  {
    id: 89,
    title: "Men Wooded Sweater (Black)",
    image: "/blackwoodie/blackwoodie1.jpg",
    slug: "men-wooded-sweater-black",
    subCatId: 6,
    catId: 1,
    description:
      "Stay warm and stylish with this men's wooded sweater in black. It's perfect for a classic and cozy look. Get it now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 31000,
    originalPrice: 41000,
    subCatName: "Wooded Sweaters",
    images: ["/blackwoodie/blackwoodie1.jpg", "/blackwoodie/blackwoodie1.jpg"],
  },
  //suits
  {
    id: 90,
    title: "Brand Men Wedding Party Suit",
    image: "/suits1/suit.jpg",
    slug: "brand-men-wedding-party-suit",
    subCatId: 7,
    catId: 1,
    description:
      "Look dashing at weddings and parties with this brand men wedding party suit. It offers a stylish and sophisticated appearance. Get it now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 337000,
    originalPrice: 557000,
    subCatName: "Wedding Suits",
    images: ["/suits1/suit.jpg", "/suits1/suit.jpg"],
  },
  {
    id: 91,
    title: "Men's Three-Piece Long Sleeve Casual Clothing Set (Light Blue)",
    image: "/suit2.jpg",
    slug: "mens-three-piece-casual-clothing-set-light-blue",
    subCatId: 7,
    catId: 1,
    description:
      "Get a complete look with this three-piece long sleeve casual clothing set in light blue. It's perfect for casual occasions and offers a comfortable fit. Grab one now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 140000,
    originalPrice: 207000,
    subCatName: "Casual Clothing Sets",
    images: ["/suit2.jpg", "/suit2.jpg"],
  },
  {
    id: 92,
    title: " Suit",
    image: "/diamond/diamond.jpg",
    slug: "diamond-men-suit",
    subCatId: 7,
    catId: 1,
    description:
      "Shine at your special events with the Diamond men suit. It offers an elegant and stylish appearance, perfect for formal gatherings. Get it now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 290000,
    originalPrice: 370000,
    subCatName: "Suits",
    images: ["/diamond/diamond.jpg", "/diamond/diamond.jpg"],
  },
  {
    id: 93,
    title: "3-in-1 Men Suit (Wooded Gray)",
    image: "/graysuit/graysuit1.jpg",
    slug: "3-in-1-men-suit-wooded-gray",
    subCatId: 7,
    catId: 1,
    description:
      "Upgrade your style with this 3-in-1 men suit in wooded gray. It offers versatility and a fashionable look. Get it now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 141000,
    originalPrice: 241000,
    subCatName: "Suits",
    images: ["/graysuit/graysuit3.jpg", "/graysuit/graysuit2.jpg"],
  },
  //wallet and belts
  {
    id: 94,
    title: "Belt & Wallet",
    image: "/wallet/wallet.jpg",
    slug: "belt-wallet",
    subCatId: 27,
    catId: 1,
    description:
      "Complete your look with this belt and wallet combo. It's a perfect choice for both style and functionality. Get it now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 20000,
    originalPrice: 357000,
    subCatName: "Belt & Wallet Sets",
    images: ["belt-wallet1.jpg", "belt-wallet2.jpg"],
  },
  {
    id: 95,
    title: "Shiny Belt and Wallet",
    image: "/wallet/wallet2.jpg",
    slug: "shiny-belt-wallet",
    subCatId: 27,
    catId: 1,
    description:
      "Add a touch of shine to your style with this shiny belt and wallet set. It's perfect for a sleek and polished look. Get one now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 18000,
    originalPrice: 27000,
    subCatName: "Belt & Wallet Sets",
    images: ["/wallet/wallet2.jpg", "/wallet/wallet2.jpg"],
  },
  {
    id: 96,
    title: "Black Wallet and Belt",
    image: "/wallet/wallet3.jpg",
    slug: "black-wallet-belt",
    subCatId: 27,
    catId: 1,
    description:
      "Stay classy with this black wallet and belt set. It offers a timeless and elegant look. Get it now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 19000,
    originalPrice: 37000,
    subCatName: "Belt & Wallet Sets",
    images: ["/wallet/wallet3.jpg", "/wallet/wallet3.jpg"],
  },
  {
    id: 97,
    title: "5 Piece Men's Gift Set: Wallet + Belt + Keychain + Pen + Tie",
    image: "/wallet/wallet4.jpg",
    slug: "mens-gift-set",
    subCatId: 27,
    catId: 1,
    description:
      "Spoil yourself or someone special with this 5 Piece Men's Gift Set. It includes a wallet, belt, keychain, pen, and tie for a complete look. Get it now at a special price!",
    hasFreeDelivery: true,
    currentPrice: 55000,
    originalPrice: 70000,
    subCatName: "Gift Sets",
    images: ["/wallet/wallet4.jpg", "gift-set1.jpg", "/wallet/wallet4.jpg"],
  },
];

// Function to convert price to USD and round off
// const convertToUsd = (priceUGX, exchangeRate) => {
//   const priceUSD = priceUGX * exchangeRate;
//   return Math.round(priceUSD * 100) / 100; // Round off to 2 decimal places
// };

// Function to round off the price in UGX
// const roundOffUgx = (price) => Math.round(price);

// Loop through each product and add priceUSD and priceKES keys
for (const product of products) {
  // Calculate price in USD
//   const priceUsdUGX = convertToUsd(product.currentPrice, ugxToUsdExchangeRate);

  // Calculate price in UGX from KES and round off
//   const priceUgxKES = roundOffUgx(product.currentPrice * kesToUgxExchangeRate);

  // Add the new keys to the product object
//   product.priceUSD = priceUsdUGX;
//   product.priceKES = priceUgxKES;
}

// Output the updated products array
// console.log(JSON.stringify(products, null, 2));

export { categories, subCategories, products };
